openapi: 3.1.0
info:
  title: Instagram Audit Connector
  version: 1.0.0
servers:
  - url: https://SEU-PROJETO.vercel.app   # <-- troque pelo seu domínio .vercel.app (sem barra no final)
paths:
  /api/ig/audit:
    get:
      operationId: getIgAudit              # <-- obrigatório para Actions
      summary: Retorna dados normalizados de um perfil do Instagram
      description: Retorna IgAuditPayload para um handle (sem @).
      parameters:
        - name: handle
          in: query
          required: true
          description: Instagram handle sem @
          schema:
            type: string
        - name: max_posts
          in: query
          required: false
          description: Quantidade máxima de posts
          schema:
            type: integer
            default: 24
      responses:
        '200':
          description: Payload padronizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IgAuditPayload'
        '400':
          description: Parâmetros ausentes ou inválidos
        '500':
          description: Erro interno
components:
  schemas:
    IgAuditPayload:
      type: object
      required: [profile, posts]
      properties:
        profile:
          type: object
          properties:
            handle: { type: string }
            name: { type: string, nullable: true }
            bio: { type: string, nullable: true }
            followers: { type: integer, nullable: true }
            following: { type: integer, nullable: true }
            posts_count: { type: integer, nullable: true }
            external_url: { type: string, nullable: true }
            is_business: { type: boolean, nullable: true }
            profile_pic_url: { type: string, nullable: true }
            categories:
              type: array
              items: { type: string }
            highlights:
              type: array
              items:
                type: object
                properties:
                  title: { type: string }
        posts:
          type: array
          items:
            type: object
            properties:
              id: { type: string, nullable: true }
              shortcode: { type: string, nullable: true }
              media_type:
                type: string
                enum: [IMAGE, VIDEO, CAROUSEL]
              caption: { type: string, nullable: true }
              timestamp: { type: string, format: date-time, nullable: true }
              like_count: { type: integer, nullable: true }
              comment_count: { type: integer, nullable: true }
              view_count: { type: integer, nullable: true }
              thumbnail_url: { type: string, nullable: true }
